### ISSUE TITLE
extension.livescript-preview fails

### ISSUE THREAD

**Issue by foxbunny** [eheitherd/vscode-livescript-preview#1]
I installed this extension on VS Code 1.10.2 on Linux (Ubuntu 16.10). When I start the command, I get the error message:

> Running the contributed command: 'extension.livescript-preview' failed

I have a `livescript` package (1.5.0) installed both globally, and locally in the project.

**Comment by eheitherd** [comment]
Thank you for reporting this issue!

I have not seen this error on Windows.
But I found the error occurs on ubuntu in VM.

I'll investigate it.

**Comment by foxbunny** [comment]
Cool. Let me know if there's any info I could provide.

**Comment by eheitherd** [comment]
I fixed the error and released 1.0.2.
Please upgrade the extension and try it!

**Comment by foxbunny** [comment]
Fantastic! Works very well now. 👍
